"""Add subscription and profile fields to users

Revision ID: 356ea6ccaab7
Revises: 8727e631688e
Create Date: 2025-07-12 21:19:11.975754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356ea6ccaab7'
down_revision = '8727e631688e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_plan', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_usage_item_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'subscription_usage_item_id')
    op.drop_column('users', 'subscription_id')
    op.drop_column('users', 'subscription_plan')
    # ### end Alembic commands ###